name: publish-release.yml

on:
  release:
    types:
      - published

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@afe4af09a72596f47d806ee5f8b2674ec07fdc73
      with:
          fetch-depth: 0

    - name: Check Version against Tag
      run: |
        echo "Checking package.json version against tag..."
        TagVersion=${{ github.event.release.tag_name }}
        PackageJsonVersion=v$(sed 's/.*"version": "\(.*\)".*/\1/;t;d' ./package.json)
        if [ "$TagVersion" != "$PackageJsonVersion" ];
        then
          echo "Version $PackageJsonVersion does not match tag $TagVersion"
          exit 1
        fi
        echo "package.json version matches tag: $TagVersion"

    - name: Publish
      env:
        PROXIMA_OSS_PACKAGE_TOKEN: ${{ secrets.PROXIMA_OSS_PACKAGE_TOKEN }}
      run: npm publish --access public
